insert into film_festival(name, country) values('아카데미 시상식', '미국');
insert into film_festival(name, country) values('칸 영화제', '프랑스');
insert into film_festival(name, country) values('베를린 영화제', '독일');
insert into film_festival(name, country) values('베니스 영화제', '이탈리아');

insert into director(name, nationality) values('캐스린 비글로우', '미국');
insert into director(name, nationality) values('톰 후퍼', '영국');
insert into director(name, nationality) values('미셸 하자나비시우스', '프랑스');
insert into director(name, nationality) values('벤 애플랙', '미국');
insert into director(name, nationality) values('스티브 맥퀸', '영국');
insert into director(name, nationality) values('알레한드로 곤잘레스 이냐리투', '멕시코');
insert into director(name, nationality) values('토마스 맥카시', '미국');
insert into director(name, nationality) values('베리 젠킨스', '미국');
insert into director(name, nationality) values('기예르모 델 토로', '멕시코');
insert into director(name, nationality) values('피터 패럴리', '미국');
insert into director(name, nationality) values('봉준호', '대한민국');
insert into director(name, nationality) values('클로이 자오', '미국');
insert into director(name, nationality) values('션 헤이더', '미국');
insert into director(name, nationality) values('라스 폰 트리에', '덴마크');
insert into director(name, nationality) values('난니 모레티', '이탈리아');
insert into director(name, nationality) values('로만 폴란스키', '폴란드');
insert into director(name, nationality) values('거스 밴 샌트', '미국');
insert into director(name, nationality) values('마이클 무어', '미국');
insert into director(name, nationality) values('다르덴 형제', '벨기에');
insert into director(name, nationality) values('켄 로치', '영국');
insert into director(name, nationality) values('크리스티안 문지우', '루마니아');
insert into director(name, nationality) values('로랑 캉테', '프랑스');
insert into director(name, nationality) values('미카엘 하네케', '오스트리아');
insert into director(name, nationality) values('아피찻퐁 위라세타꾼', '태국');
insert into director(name, nationality) values('테런스 맬릭', '미국');
insert into director(name, nationality) values('압델라티프 케시시', '프랑스');
insert into director(name, nationality) values('누리 빌게 제일란', '터키');
insert into director(name, nationality) values('자크 오디아르', '프랑스');
insert into director(name, nationality) values('루벤 외스틀룬드', '스웨덴');
insert into director(name, nationality) values('고레에다 히로카즈', '일본');
insert into director(name, nationality) values('쥘리아 뒤쿠르노', '프랑스');
insert into director(name, nationality) values('폴 토머스 앤더슨', '미국');
insert into director(name, nationality) values('파트리스 셰로', '프랑스');
insert into director(name, nationality) values('미야자키 히야오', '일본');
insert into director(name, nationality) values('폴 그린그래스', '영국');
insert into director(name, nationality) values('마이클 윈터보텀', '영국');
insert into director(name, nationality) values('파티 아킨', '독일');
insert into director(name, nationality) values('마크 돈퍼드메이', '남아프리카 공화국');
insert into director(name, nationality) values('야스밀라 주바니치', '보스니아 헤르체고비나');
insert into director(name, nationality) values('왕취안안', '중국');
insert into director(name, nationality) values('조제 파질랴', '브라질');
insert into director(name, nationality) values('클라우디아 로사', '페루');
insert into director(name, nationality) values('세미 카플라노글루', '터키');
insert into director(name, nationality) values('아스가르 파르하디', '이란');
insert into director(name, nationality) values('파올로 타비아니 형제', '이탈리아');
insert into director(name, nationality) values('칼린 페터 네쩌', '루마니아');
insert into director(name, nationality) values('댜오이난', '중국');
insert into director(name, nationality) values('자파르 파나히', '이란');
insert into director(name, nationality) values('잔프랑코 로시', '이탈리아');
insert into director(name, nationality) values('일디코 엔예디', '헝가리');
insert into director(name, nationality) values('애디너 핀틸리', '루마니아');
insert into director(name, nationality) values('나다브 라피드', '이스라엘');
insert into director(name, nationality) values('모하마드 라술로프', '이란');
insert into director(name, nationality) values('라드 주드', '루마니아');
insert into director(name, nationality) values('카를라 시몬', '스페인');
insert into director(name, nationality) values('미라 네어', '인도');
insert into director(name, nationality) values('피터 뮬란', '영국');
insert into director(name, nationality) values('안드레이 즈비아긴체프', '러시아');
insert into director(name, nationality) values('마이크 리', '영국');
insert into director(name, nationality) values('이안', '중국');
insert into director(name, nationality) values('자장커', '중국');
insert into director(name, nationality) values('대런 애러노프스키', '미국');
insert into director(name, nationality) values('사무엘 마오즈', '이스라엘');
insert into director(name, nationality) values('소피아 코폴라', '미국');
insert into director(name, nationality) values('알렉산드르 소쿠로프', '러시아');
insert into director(name, nationality) values('김기덕', '대한민국');
insert into director(name, nationality) values('로이 앤더슨', '스웨덴');
insert into director(name, nationality) values('로렌소 비가스', '베네수엘라');
insert into director(name, nationality) values('라브 디아즈', '필리핀');
insert into director(name, nationality) values('알폰소 쿠아론', '멕시코');
insert into director(name, nationality) values('토드 필립스', '미국');
insert into director(name, nationality) values('오드리 디완', '프랑스');
insert into director(name, nationality) values('로라 포이트러스', '미국');

insert into film(name, director_id) values('허트 로커', 1);
insert into film(name, director_id) values('킹스 스피치', 2);
insert into film(name, director_id) values('아티스트', 3);
insert into film(name, director_id) values('아르고', 4);
insert into film(name, director_id) values('노예 12년', 5);
insert into film(name, director_id) values('버드맨', 6);
insert into film(name, director_id) values('스포트라이트', 7);
insert into film(name, director_id) values('문라이트', 8);
insert into film(name, director_id) values('셰이프 오브 워터: 사랑의 모양', 9);
insert into film(name, director_id) values('그린 북', 10);
insert into film(name, director_id) values('기생충', 11);
insert into film(name, director_id) values('노매드랜드', 12);
insert into film(name, director_id) values('코다', 13);
insert into film(name, director_id) values('어둠 속의 댄서', 14);
insert into film(name, director_id) values('아들의 방', 15);
insert into film(name, director_id) values('피아니스트', 16);
insert into film(name, director_id) values('엘리펀트', 17);
insert into film(name, director_id) values('화씨 9/11', 18);
insert into film(name, director_id) values('더 차일드', 19);
insert into film(name, director_id) values('보리밭을 흔드는 바람', 20);
insert into film(name, director_id) values('4개월, 3주… 그리고 2일', 21);
insert into film(name, director_id) values('클래스', 22);
insert into film(name, director_id) values('하얀 리본', 23);
insert into film(name, director_id) values('엉클 분미', 24);
insert into film(name, director_id) values('트리 오브 라이프', 25);
insert into film(name, director_id) values('아무르', 23);
insert into film(name, director_id) values('가장 따뜻한 색, 블루', 26);
insert into film(name, director_id) values('윈터 슬립', 27);
insert into film(name, director_id) values('디판', 28);
insert into film(name, director_id) values('나, 다니엘 블레이크', 20);
insert into film(name, director_id) values('더 스퀘어', 29);
insert into film(name, director_id) values('어느 가족', 30);
insert into film(name, director_id) values('티탄', 31);
insert into film(name, director_id) values('트라이앵글 오브 새드니스', 29);
insert into film(name, director_id) values('매그놀리아', 32);
insert into film(name, director_id) values('정사', 33);
insert into film(name, director_id) values('센과 치히로의 행방불명', 34);
insert into film(name, director_id) values('블러디 선데이', 35);
insert into film(name, director_id) values('인 디스 월드', 36);
insert into film(name, director_id) values('미치고 싶을 때', 37);
insert into film(name, director_id) values('카르멘', 38);
insert into film(name, director_id) values('그르바비차', 39);
insert into film(name, director_id) values('투야의 결혼', 40);
insert into film(name, director_id) values('엘리트 스쿼드', 41);
insert into film(name, director_id) values('밀크 오브 소로우 - 슬픈 모유', 42);
insert into film(name, director_id) values('허니', 43);
insert into film(name, director_id) values('씨민과 나데르의 별거', 44);
insert into film(name, director_id) values('시저는 죽어야 한다', 45);
insert into film(name, director_id) values('아들의 자리', 46);
insert into film(name, director_id) values('백일염화', 47);
insert into film(name, director_id) values('택시', 48);
insert into film(name, director_id) values('화염의 바다', 49);
insert into film(name, director_id) values('우리는 같은 꿈을 꾼다', 50);
insert into film(name, director_id) values('터치 미 낫', 51);
insert into film(name, director_id) values('시너님즈', 52);
insert into film(name, director_id) values('사탄은 없다', 53);
insert into film(name, director_id) values('배드 럭 뱅잉', 54);
insert into film(name, director_id) values('알카라스의 여름', 55);
insert into film(name, director_id) values('서클', 48);
insert into film(name, director_id) values('몬순 웨딩', 56);
insert into film(name, director_id) values('막달레나 시스터즈', 57);
insert into film(name, director_id) values('리턴', 58);
insert into film(name, director_id) values('베라 드레이크', 59);
insert into film(name, director_id) values('브로크백 마운틴', 60);
insert into film(name, director_id) values('스틸 라이프', 61);
insert into film(name, director_id) values('색, 계', 60);
insert into film(name, director_id) values('더 레슬러', 62);
insert into film(name, director_id) values('레바논', 63);
insert into film(name, director_id) values('섬웨어', 64);
insert into film(name, director_id) values('파우스트', 65);
insert into film(name, director_id) values('피에타', 66);
insert into film(name, director_id) values('성스러운 도로', 49);
insert into film(name, director_id) values('비둘기, 가지에 앉아 존재를 성찰하다', 67);
insert into film(name, director_id) values('프롬 어파', 68);
insert into film(name, director_id) values('떠나간 여인', 69);
insert into film(name, director_id) values('로마', 70);
insert into film(name, director_id) values('조커', 71);
insert into film(name, director_id) values('레벤느망', 72);
insert into film(name, director_id) values('올 더 뷰티 앤드 더 블러드셰드', 73);

insert into film_gender(grade, gender, film_id) values(8.32, 'M', 1);
insert into film_gender(grade, gender, film_id) values(8.84, 'F', 1);
insert into film_gender(grade, gender, film_id) values(8.04, 'M', 2);
insert into film_gender(grade, gender, film_id) values(8.7, 'F', 2);
insert into film_gender(grade, gender, film_id) values(8.33, 'M', 3);
insert into film_gender(grade, gender, film_id) values(8.33, 'F', 3);
insert into film_gender(grade, gender, film_id) values(8.1, 'M', 4);
insert into film_gender(grade, gender, film_id) values(8.74, 'F', 4);
insert into film_gender(grade, gender, film_id) values(8.3, 'M', 5);
insert into film_gender(grade, gender, film_id) values(8.42, 'F', 5);
insert into film_gender(grade, gender, film_id) values(8.47, 'M', 6);
insert into film_gender(grade, gender, film_id) values(8.47, 'F', 6);
insert into film_gender(grade, gender, film_id) values(8.82, 'M', 7);
insert into film_gender(grade, gender, film_id) values(9.01, 'F', 7);
insert into film_gender(grade, gender, film_id) values(8.29, 'M', 8);
insert into film_gender(grade, gender, film_id) values(8.48, 'F', 8);
insert into film_gender(grade, gender, film_id) values(8.54, 'M', 9);
insert into film_gender(grade, gender, film_id) values(8.79, 'F', 9);
insert into film_gender(grade, gender, film_id) values(9.52, 'M', 10);
insert into film_gender(grade, gender, film_id) values(9.57, 'F', 10);
insert into film_gender(grade, gender, film_id) values(9.14, 'M', 11);
insert into film_gender(grade, gender, film_id) values(9, 'F', 11);
insert into film_gender(grade, gender, film_id) values(8.62, 'M', 12);
insert into film_gender(grade, gender, film_id) values(8.56, 'F', 12);
insert into film_gender(grade, gender, film_id) values(8.56, 'M', 13);
insert into film_gender(grade, gender, film_id) values(8.98, 'F', 13);
insert into film_gender(grade, gender, film_id) values(9.2, 'M', 14);
insert into film_gender(grade, gender, film_id) values(8.67, 'F', 14);
insert into film_gender(grade, gender, film_id) values(7.94, 'M', 15);
insert into film_gender(grade, gender, film_id) values(8.3, 'F', 15);
insert into film_gender(grade, gender, film_id) values(8.21, 'M', 16);
insert into film_gender(grade, gender, film_id) values(8.21, 'F', 16);
insert into film_gender(grade, gender, film_id) values(7.7, 'M', 17);
insert into film_gender(grade, gender, film_id) values(8.44, 'F', 17);
insert into film_gender(grade, gender, film_id) values(8.52, 'M', 18);
insert into film_gender(grade, gender, film_id) values(8.81, 'F', 18);
insert into film_gender(grade, gender, film_id) values(8.24, 'M', 19);
insert into film_gender(grade, gender, film_id) values(8.24, 'F', 19);
insert into film_gender(grade, gender, film_id) values(8.3, 'M', 20);
insert into film_gender(grade, gender, film_id) values(9.04, 'F', 20);
insert into film_gender(grade, gender, film_id) values(7.76, 'M', 21);
insert into film_gender(grade, gender, film_id) values(7.57, 'F', 21);
insert into film_gender(grade, gender, film_id) values(7.88, 'M', 22);
insert into film_gender(grade, gender, film_id) values(7.88, 'F', 22);
insert into film_gender(grade, gender, film_id) values(7.91, 'M', 23);
insert into film_gender(grade, gender, film_id) values(7.91, 'F', 23);
insert into film_gender(grade, gender, film_id) values(9.67, 'M', 24);
insert into film_gender(grade, gender, film_id) values(8.4, 'F', 24);
insert into film_gender(grade, gender, film_id) values(6.91, 'M', 25);
insert into film_gender(grade, gender, film_id) values(7.12, 'F', 25);
insert into film_gender(grade, gender, film_id) values(8.26, 'M', 26);
insert into film_gender(grade, gender, film_id) values(8.89, 'F', 26);
insert into film_gender(grade, gender, film_id) values(8.94, 'M', 27);
insert into film_gender(grade, gender, film_id) values(8.96, 'F', 27);
insert into film_gender(grade, gender, film_id) values(8.74, 'M', 28);
insert into film_gender(grade, gender, film_id) values(8.33, 'F', 28);
insert into film_gender(grade, gender, film_id) values(8.17, 'M', 29);
insert into film_gender(grade, gender, film_id) values(9.5, 'F', 29);
insert into film_gender(grade, gender, film_id) values(9.1, 'M', 30);
insert into film_gender(grade, gender, film_id) values(9.41, 'F', 30);
insert into film_gender(grade, gender, film_id) values(8.16, 'M', 31);
insert into film_gender(grade, gender, film_id) values(8, 'F', 31);
insert into film_gender(grade, gender, film_id) values(9.22, 'M', 32);
insert into film_gender(grade, gender, film_id) values(9.25, 'F', 32);
insert into film_gender(grade, gender, film_id) values(7.11, 'M', 33);
insert into film_gender(grade, gender, film_id) values(7.11, 'F', 33);
insert into film_gender(grade, gender, film_id) values(7.8, 'M', 34);
insert into film_gender(grade, gender, film_id) values(7.8, 'F', 34);
insert into film_gender(grade, gender, film_id) values(8.85, 'M', 35);
insert into film_gender(grade, gender, film_id) values(9.4, 'F', 35);
insert into film_gender(grade, gender, film_id) values(6.1, 'M', 36);
insert into film_gender(grade, gender, film_id) values(6.1, 'F', 36);
insert into film_gender(grade, gender, film_id) values(9.35, 'M', 37);
insert into film_gender(grade, gender, film_id) values(9.68, 'F', 37);
insert into film_gender(grade, gender, film_id) values(8.67, 'M', 38);
insert into film_gender(grade, gender, film_id) values(9.15, 'F', 38);
insert into film_gender(grade, gender, film_id) values(8.16, 'M', 39);
insert into film_gender(grade, gender, film_id) values(9.47, 'F', 39);
insert into film_gender(grade, gender, film_id) values(7.63, 'M', 40);
insert into film_gender(grade, gender, film_id) values(8.63, 'F', 40);
insert into film_gender(grade, gender, film_id) values(7.4, 'M', 41);
insert into film_gender(grade, gender, film_id) values(6.5, 'F', 41);
insert into film_gender(grade, gender, film_id) values(7.2, 'M', 42);
insert into film_gender(grade, gender, film_id) values(7.2, 'F', 42);
insert into film_gender(grade, gender, film_id) values(8.23, 'M', 43);
insert into film_gender(grade, gender, film_id) values(9.14, 'F', 43);
insert into film_gender(grade, gender, film_id) values(8.6, 'M', 44);
insert into film_gender(grade, gender, film_id) values(7.18, 'F', 44);
insert into film_gender(grade, gender, film_id) values(9.3, 'M', 45);
insert into film_gender(grade, gender, film_id) values(9.3, 'F', 45);
insert into film_gender(grade, gender, film_id) values(7.35, 'M', 46);
insert into film_gender(grade, gender, film_id) values(8.67, 'F', 46);
insert into film_gender(grade, gender, film_id) values(9, 'M', 47);
insert into film_gender(grade, gender, film_id) values(9, 'F', 47);
insert into film_gender(grade, gender, film_id) values(7.2, 'M', 48);
insert into film_gender(grade, gender, film_id) values(7.2, 'F', 48);
insert into film_gender(grade, gender, film_id) values(6.8, 'M', 49);
insert into film_gender(grade, gender, film_id) values(6.8, 'F', 49);
insert into film_gender(grade, gender, film_id) values(7, 'M', 50);
insert into film_gender(grade, gender, film_id) values(7, 'F', 50);
insert into film_gender(grade, gender, film_id) values(8.75, 'M', 51);
insert into film_gender(grade, gender, film_id) values(8.75, 'F', 51);
insert into film_gender(grade, gender, film_id) values(9, 'M', 52);
insert into film_gender(grade, gender, film_id) values(9, 'F', 52);
insert into film_gender(grade, gender, film_id) values(8.3, 'M', 53);
insert into film_gender(grade, gender, film_id) values(7.79, 'F', 53);
insert into film_gender(grade, gender, film_id) values(5.6, 'M', 54);
insert into film_gender(grade, gender, film_id) values(5.6, 'F', 54);
insert into film_gender(grade, gender, film_id) values(6.8, 'M', 55);
insert into film_gender(grade, gender, film_id) values(6.8, 'F', 55);
insert into film_gender(grade, gender, film_id) values(8, 'M', 56);
insert into film_gender(grade, gender, film_id) values(8, 'F', 56);
insert into film_gender(grade, gender, film_id) values(6.28, 'M', 57);
insert into film_gender(grade, gender, film_id) values(6.33, 'F', 57);
insert into film_gender(grade, gender, film_id) values(7.48, 'M', 58);
insert into film_gender(grade, gender, film_id) values(7.54, 'F', 58);
insert into film_gender(grade, gender, film_id) values(8, 'M', 59);
insert into film_gender(grade, gender, film_id) values(8, 'F', 59);
insert into film_gender(grade, gender, film_id) values(8.2, 'M', 60);
insert into film_gender(grade, gender, film_id) values(8.2, 'F', 60);
insert into film_gender(grade, gender, film_id) values(8.48, 'M', 61);
insert into film_gender(grade, gender, film_id) values(8.78, 'F', 61);
insert into film_gender(grade, gender, film_id) values(8.1, 'M', 62);
insert into film_gender(grade, gender, film_id) values(9.18, 'F', 62);
insert into film_gender(grade, gender, film_id) values(7.7, 'M', 63);
insert into film_gender(grade, gender, film_id) values(7.7, 'F', 63);
insert into film_gender(grade, gender, film_id) values(7.95, 'M', 64);
insert into film_gender(grade, gender, film_id) values(9.11, 'F', 64);
insert into film_gender(grade, gender, film_id) values(8.42, 'M', 65);
insert into film_gender(grade, gender, film_id) values(7.72, 'F', 65);
insert into film_gender(grade, gender, film_id) values(8.07, 'M', 66);
insert into film_gender(grade, gender, film_id) values(8.97, 'F', 66);
insert into film_gender(grade, gender, film_id) values(8.74, 'M', 67);
insert into film_gender(grade, gender, film_id) values(8.58, 'F', 67);
insert into film_gender(grade, gender, film_id) values(6.1, 'M', 68);
insert into film_gender(grade, gender, film_id) values(6.1, 'F', 68);
insert into film_gender(grade, gender, film_id) values(7.7, 'M', 69);
insert into film_gender(grade, gender, film_id) values(7.7, 'F', 69);
insert into film_gender(grade, gender, film_id) values(7.3, 'M', 70);
insert into film_gender(grade, gender, film_id) values(7.3, 'F', 70);
insert into film_gender(grade, gender, film_id) values(7.41, 'M', 71);
insert into film_gender(grade, gender, film_id) values(8.27, 'F', 71);
insert into film_gender(grade, gender, film_id) values(6.4, 'M', 72);
insert into film_gender(grade, gender, film_id) values(6.4, 'F', 72);
insert into film_gender(grade, gender, film_id) values(9.5, 'M', 73);
insert into film_gender(grade, gender, film_id) values(9.5, 'F', 73);
insert into film_gender(grade, gender, film_id) values(6.6, 'M', 74);
insert into film_gender(grade, gender, film_id) values(6.6, 'F', 74);
insert into film_gender(grade, gender, film_id) values(9, 'M', 75);
insert into film_gender(grade, gender, film_id) values(9, 'F', 75);
insert into film_gender(grade, gender, film_id) values(8.3, 'M', 76);
insert into film_gender(grade, gender, film_id) values(9.42, 'F', 76);
insert into film_gender(grade, gender, film_id) values(8.74, 'M', 77);
insert into film_gender(grade, gender, film_id) values(8.31, 'F', 77);
insert into film_gender(grade, gender, film_id) values(7.17, 'M', 78);
insert into film_gender(grade, gender, film_id) values(8.75, 'F', 78);
insert into film_gender(grade, gender, film_id) values(7.8, 'M', 79);
insert into film_gender(grade, gender, film_id) values(7.8, 'F', 79);

insert into film_hit(sales, film_id) values(42079220, 1);
insert into film_hit(sales, film_id) values(414211549, 2);
insert into film_hit(sales, film_id) values(138000000, 3);
insert into film_hit(sales, film_id) values(232325503, 4);
insert into film_hit(sales, film_id) values(187733202, 5);
insert into film_hit(sales, film_id) values(103200000, 6);
insert into film_hit(sales, film_id) values(88346473, 7);
insert into film_hit(sales, film_id) values(5000000, 8);
insert into film_hit(sales, film_id) values(19500000, 9);
insert into film_hit(sales, film_id) values(23000000, 10);
insert into film_hit(sales, film_id) values(269169009, 11);
insert into film_hit(sales, film_id) values(39458207, 12);
insert into film_hit(sales, film_id) values(1608201, 13);
insert into film_hit(sales, film_id) values(45600000, 14);
insert into film_hit(sales, film_id) values(11767402, 15);
insert into film_hit(sales, film_id) values(120072577, 16);
insert into film_hit(sales, film_id) values(0, 17);
insert into film_hit(sales, film_id) values(222446882, 18);
insert into film_hit(sales, film_id) values(0, 19);
insert into film_hit(sales, film_id) values(22903165, 20);
insert into film_hit(sales, film_id) values(10174839, 21);
insert into film_hit(sales, film_id) values(0, 22);
insert into film_hit(sales, film_id) values(19319444, 23);
insert into film_hit(sales, film_id) values(0, 24);
insert into film_hit(sales, film_id) values(61700000, 25);
insert into film_hit(sales, film_id) values(29900000, 26);
insert into film_hit(sales, film_id) values(19465835, 27);
insert into film_hit(sales, film_id) values(4018705, 28);
insert into film_hit(sales, film_id) values(5562275, 29);
insert into film_hit(sales, film_id) values(15793051, 30);
insert into film_hit(sales, film_id) values(9493791, 31);
insert into film_hit(sales, film_id) values(67998954, 32);
insert into film_hit(sales, film_id) values(0, 33);
insert into film_hit(sales, film_id) values(0, 34);
insert into film_hit(sales, film_id) values(48451803, 35);
insert into film_hit(sales, film_id) values(0, 36);
insert into film_hit(sales, film_id) values(365481131, 37);
insert into film_hit(sales, film_id) values(1758689, 38);
insert into film_hit(sales, film_id) values(0, 39);
insert into film_hit(sales, film_id) values(11000000, 40);
insert into film_hit(sales, film_id) values(0, 41);
insert into film_hit(sales, film_id) values(0, 42);
insert into film_hit(sales, film_id) values(0, 43);
insert into film_hit(sales, film_id) values(14000000, 44);
insert into film_hit(sales, film_id) values(0, 45);
insert into film_hit(sales, film_id) values(0, 46);
insert into film_hit(sales, film_id) values(22926076, 47);
insert into film_hit(sales, film_id) values(0, 48);
insert into film_hit(sales, film_id) values(0, 49);
insert into film_hit(sales, film_id) values(0, 50);
insert into film_hit(sales, film_id) values(0, 51);
insert into film_hit(sales, film_id) values(0, 52);
insert into film_hit(sales, film_id) values(2000000, 53);
insert into film_hit(sales, film_id) values(0, 54);
insert into film_hit(sales, film_id) values(0, 55);
insert into film_hit(sales, film_id) values(0, 56);
insert into film_hit(sales, film_id) values(0, 57);
insert into film_hit(sales, film_id) values(2352140, 58);
insert into film_hit(sales, film_id) values(0, 59);
insert into film_hit(sales, film_id) values(0, 60);
insert into film_hit(sales, film_id) values(0, 61);
insert into film_hit(sales, film_id) values(8482993, 62);
insert into film_hit(sales, film_id) values(0, 63);
insert into film_hit(sales, film_id) values(178062759, 64);
insert into film_hit(sales, film_id) values(2504465, 65);
insert into film_hit(sales, film_id) values(67091915, 66);
insert into film_hit(sales, film_id) values(44734660, 67);
insert into film_hit(sales, film_id) values(0, 68);
insert into film_hit(sales, film_id) values(0, 69);
insert into film_hit(sales, film_id) values(0, 70);
insert into film_hit(sales, film_id) values(6616296, 71);
insert into film_hit(sales, film_id) values(0, 72);
insert into film_hit(sales, film_id) values(0, 73);
insert into film_hit(sales, film_id) values(0, 74);
insert into film_hit(sales, film_id) values(0, 75);
insert into film_hit(sales, film_id) values(238151, 76);
insert into film_hit(sales, film_id) values(1074445730, 77);
insert into film_hit(sales, film_id) values(1029414, 78);
insert into film_hit(sales, film_id) values(0, 79);

insert into academy_best_award(year, round, film_id, film_festival_id) values(2010, 82, 1, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2011, 83, 2, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2012, 84, 3, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2013, 85, 4, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2014, 86, 5, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2015, 87, 6, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2016, 88, 7, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2017, 89, 8, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2018, 90, 9, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2019, 91, 10, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2020, 92, 11, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2021, 93, 12, 1);
insert into academy_best_award(year, round, film_id, film_festival_id) values(2022, 94, 13, 1);

insert into cannes_best_award(year, round, film_id, film_festival_id) values(2000, 53, 14, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2001, 54, 15, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2002, 55, 16, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2003, 56, 17, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2004, 57, 18, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2005, 58, 19, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2006, 59, 20, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2007, 60, 21, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2008, 61, 22, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2009, 62, 23, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2010, 63, 24, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2011, 64, 25, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2012, 65, 26, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2013, 66, 27, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2014, 67, 28, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2015, 68, 29, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2016, 69, 30, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2017, 70, 31, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2018, 71, 32, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2019, 72, 11, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2021, 74, 33, 2);
insert into cannes_best_award(year, round, film_id, film_festival_id) values(2022, 75, 34, 2);

insert into berlin_best_award(year, round, film_id, film_festival_id) values(2000, 50, 35, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2001, 51, 36, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2002, 52, 37, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2002, 52, 38, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2003, 53, 39, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2004, 54, 40, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2005, 55, 41, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2006, 56, 42, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2007, 57, 43, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2008, 58, 44, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2009, 59, 45, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2010, 60, 46, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2011, 61, 47, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2012, 62, 48, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2013, 63, 49, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2014, 64, 50, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2015, 65, 51, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2016, 66, 52, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2017, 67, 53, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2018, 68, 54, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2019, 69, 55, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2020, 70, 56, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2021, 71, 57, 3);
insert into berlin_best_award(year, round, film_id, film_festival_id) values(2022, 72, 58, 3);

insert into venice_best_award(year, round, film_id, film_festival_id) values(2000, 57, 59, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2001, 58, 60, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2002, 59, 61, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2003, 60, 62, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2004, 61, 63, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2005, 62, 64, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2006, 63, 65, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2007, 64, 66, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2008, 65, 67, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2009, 66, 68, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2010, 67, 69, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2011, 68, 70, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2012, 69, 71, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2013, 70, 72, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2014, 71, 73, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2015, 72, 74, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2016, 73, 75, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2017, 74, 9, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2018, 75, 76, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2019, 76, 77, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2020, 77, 12, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2021, 78, 78, 4);
insert into venice_best_award(year, round, film_id, film_festival_id) values(2022, 79, 79, 4);
